[package]
name = "k9r-socket-server"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"
repository = "https://github.com/CKAY-9/k9r"

[dependencies]
reqwest = "0.12.14"
serde = "1.0.219"
serde_json = "1.0.140"
tungstenite = "0.26.2"
